from __future__ import annotations
from typing import Protocol, AsyncIterator, runtime_checkable
from .models import Task, WorkerResult, Event


@runtime_checkable
class WorkerAdapter(Protocol):
    worker_id: str
    display_name: str

    async def submit_task(self, task: Task) -> str: ...
    async def stream_events(self, task_id: str) -> AsyncIterator[Event]: ...
    async def get_result(self, task_id: str) -> WorkerResult: ...
    async def cancel_task(self, task_id: str) -> None: ...
    async def health(self) -> dict: ...
